### ISSUE TITLE
Bound inputs in Source and Sink boundaries

### ISSUE THREAD

**Issue by rfranke** [DLR-SR/ThermofluidStream#105]
First of all congratulations to this nice library!

One small issue: `ThermofluidStream.Boundaries.Source` and `ThermofluidStream.Boundaries.Sink` offer signal inputs that are defined with the strange pattern:
```Modelica
model BoundInput
  Real p0;
  input Real p0_var = p0;
end BoundInput;
```
This model generates in OpenModelica:
```
Error: Too few equations, under-determined system. The model has 0 equation(s) and 1 variable(s).
Warning: Variable p0 does not have any remaining equation to be solved in.
```
because the input is considered a known variable and together with the input also the binding is removed from the system of unknowns and equations.
Dymola appears to do the same:
```
Warning: The input p0_var had a binding equation.
It will not be treated as an input - use a literal start-attribute if you want to keep it as input and
provide a default value (an input is intended to get its value externally).
Error: The problem is structurally singular. ... 1 scalar Real equations are missing for the variables or its derivatives.
```

The problem doesn't show up as Source and Sink never run as top-level models. It shows up when attempting to expose their connectors in FMI export, [see](https://github.com/OpenModelica/OpenModelica/issues/10599).

It also shows up when setting `pressureFromInput=true` and checking the Source or Sink model with your tool of choice.

A small change to `ThermofluidStream.Boundaries.Sink` (and `ThermofluidStream.Boundaries.Source` accordingly) would avoid the problem:
- remove the binding
- turn p0 into a connector and connect it to p0_var
- (use p0_par as start for p0_var so that it has a default value when used and left unconnected)
```diff
@@ -16,11 +16,11 @@ the outlet the sink is connected to.
 
   Interfaces.Inlet inlet(redeclare package Medium = Medium)
     annotation (Placement(transformation(extent={{-114,-10},
             {-94,10}}), iconTransformation(extent={{-120,-20},{-80,20}})));
 
-  Modelica.Blocks.Interfaces.RealInput p0_var(unit="Pa")=p0 if pressureFromInput "Pressure setpoint [Pa]"
+  Modelica.Blocks.Interfaces.RealInput p0_var(unit="Pa", start=p0_par) if pressureFromInput "Pressure setpoint [Pa]"
     annotation (Placement(
         transformation(
         extent={{-20,-20},{20,20}},
         rotation=180,
         origin={20,0}), iconTransformation(
@@ -29,16 +29,17 @@ the outlet the sink is connected to.
         origin={20,0})));
 
 protected
   outer DropOfCommons dropOfCommons;
 
-  SI.Pressure p0;
+  Modelica.Blocks.Interfaces.RealInput p0(unit="Pa");
   SI.Pressure r;
 
   SI.Pressure p = Medium.pressure(inlet.state);
 
 equation
+  connect(p0_var, p0);
   if not pressureFromInput then
     p0 = p0_par;
   end if;
 
   der(inlet.m_flow)*L = inlet.r - r;
```
Could such a change be introduced?

**Comment by rfranke** [comment]
If someone works on this, it would be nice to also get input unit conversions from bar and °C, as already offered by the MultiSensor models for outputs.

**Comment by tobolar** [comment]
Principally the same holds for `m_flow_set` and `V_flow_set` when `setpointFromInput = true` in `TFS.FlowControl.MCV`.
