### ISSUE TITLE
PCV. mo missing Xi_out=Xi_in

### ISSUE THREAD

**Issue by FrancNep** [DLR-SR/ThermofluidStream#148]
Hi, Thank s for this great library.

Into the PCV.mo model, it miss the equation "Xi_out=Xi_in"

Best regards,

François

**Comment by tobolar** [comment]
Can you explain this in more detail? The model `TFS.FlowControl.PCV` seems to be equation-balanced.

**Comment by FrancNep** [comment]
Hi, 

the equation "Xi_out=Xi_in" has been forgotten (see the other models like partialValve.mo, MCV.mo...). Currently, the model TFS.FlowControl.PCV.mo is equation-balanced for a puresubstance, not for a mixture.

Best regards,

François
