### ISSUE TITLE
"assert" Volume models 

### ISSUE THREAD

**Issue by FrancNep** [DLR-SR/ThermofluidStream#149]
Hi,

For the differents models of volume, 

 _assert(abs(Medium.density_derp_h(medium.state)) > 1e-12, "The simple Volume model should not be used with incompressible or nearly incompressible media. Consider using the FlexVolume instead.");_

should be replaced, to be coherent, by : 

 _assert(abs(density_derp_h_from_media) > 1e-12,The simple Volume model should not be used with incompressible or nearly incompressible media. Consider using the FlexVolume instead."), dropOfCommons.assertionLevel);_

Best regards,

François

**Comment by nieweber** [comment]
> abs(density_derp_h_from_media) > 1e-12

`density_derp_h_from_media` is a Boolean parameter that can be set by the user, maybe you have mistaken that?

Did you intend to ask for putting the `dropOfCommons.assertionLevel` at the end of the assert?
