### ISSUE TITLE
Several models in ThermoFluidStream appear to have parameters without binding and without explicitly set start value

### ISSUE THREAD

**Issue by casella** [DLR-SR/ThermofluidStream#180]
MLS 3.5 [Section 8.6](https://specification.modelica.org/maint/3.5/equations.html#initialization-initial-equation-and-initial-algorithm) states:

> If a parameter has a _modifier_ for the start attribute, does not have `fixed = false`, and neither has a binding equation nor is part of a record having a binding equation, the modifier for the start attribute can be used to add a parameter binding equation assigning the parameter to that start value. In this case a diagnostic message is recommended in a simulation model.

So if the unbound parameter doesn't have an explicit modifier for the start attribute, the model is invalid. This rule is enforced strictly in OMC 1.23.0 since we fixed OpenModelica/OpenModelica#10386. Other tools are more lenient, but I believe accepting parameters without bindings and explicitly set default values to be zero is really not a good idea.

If you check the latest [OMC report](https://libraries.openmodelica.org/branches/master/ThermofluidStream/ThermofluidStream.html), there are 10 models failing in the frontend, all for the [similar reasons](https://libraries.openmodelica.org/branches/master/ThermofluidStream/files/ThermofluidStream_ThermofluidStream.Examples.HeatPump.err):
```
[/home/hudson/saved_omc/libraries/.openmodelica/libraries/ThermofluidStream 1.1.0-main/FlowControl/BasicControlValve.mo:22:3-23:88:writable]
Error: Parameter controlValve.Cvs_US has neither value nor start value, and is fixed during initialization (fixed=true).
```
If you want those parameters to get a value of zero (with a warning, as mandated by the MLS), please add an explicit modifier `start = 0` to their declarations. We are going to release 1.23.0 in a few weeks, so it would be nice to have a patch release of your library by then.

Thanks!

**Comment by tobolar** [comment]
IMO similarity to #171 

Probably cause due to parameters `Kvs`, `Cvs_US` and `Cvs_UK` in [ThermofluidStream/FlowControl/BasicControlValve.mo](https://github.com/DLR-SR/ThermofluidStream/blob/34809364be2b638852f10e3ba5d8fccacec4a5d8/ThermofluidStream/FlowControl/BasicControlValve.mo#L19) ff.

**Comment by casella** [comment]
Sorry, I forgot I had already opened #171...
