### ISSUE TITLE
Top-level directory is missing

### ISSUE THREAD

**Issue by casella** [DLR-SR/ThermofluidStream#2]
According to [Section 18.8.3 of the Specification](https://specification.modelica.org/maint/3.5/annotations.html#mapping-of-versions-to-file-system), the top-level `package.mo` file should be contained in a directory named `ThermofluidStream`, or possibly `ThermofluidStream 0.1`. Unfortunately, there is no such top-level directory in the repo, so the containing directory name happens to be whatever the git tool you use thinks. For example, if I download a zip file with GIT, it is named ThermofluidStream-main, which is not according to the standard. If I clone the library on my pc, it is up to me to give the proper name when I run git clone.

LICENSE and README.md should probably be outside this directory, and instead show up at the top.

Could you please fix this?

Thanks!

**Comment by casella** [comment]
@sjoelund, when this is fixed, could you add the library to the OpenModelica library testsuite? Thanks!

**Comment by mimeissner** [comment]
I added the top-level directory. Additionally to LICENSE and README.md I moved the .gitignore to the top level.

**Comment by sjoelund** [comment]
> @sjoelund, what is missing or wrong there?

Making older OpenModelica versions load the libraries. They are stored on disk as semantic versions which are not according to Modelica spec.

**Comment by dzimmer** [comment]
The issue is already closed.

Martin Sjölund ***@***.***> schrieb am Di., 11. Mai 2021,
17:26:
