### ISSUE TITLE
problems loading latest version of ThermoFluidStream 

### ISSUE THREAD

**Issue by Flauipaui** [DLR-SR/ThermofluidStream#34]
Hello, 

i have problems loading the latest version of ThermoFluidStream Library (commit : c8ceaec) into OpenModelica Nightly Build v1.19.0-dev-464-g0e5320a867.

[3] 11:10:32 Syntax
[C:/Users/[...]/07_ThermofluidStream-main/ThermofluidStream/Boundaries/Internal/PartialVolume.mo: 114:1-114:1]: No viable alternative near token: <

[4] 11:10:32 Skripting
Failed to load package ThermofluidStream () using MODELICAPATH C:/Users/[...]/07_ThermofluidStream-main/.

Does someone experience the same problems?

Bests,

**Comment by mimeissner** [comment]
Hi, 

I am at OpenModelica v1.19.0-dev-448-g979332e586 and I can open the laterst version of the Library. A library check in Dymola also goes through. 

Is it possible that you might have a merge conflict after a pull? This would introduce in the code somthing like: 

<<<<<<<<<<<<<<< HEAD 
SOMECODE
============
SOMECODE
>>>>>>>>>>>>>>> SOMEHASH 

this could explain your error message. Could you confirm if you have a merge condflict and try out cloning the librarby into a new temporary folder and try opening it freshly cloned?

**Comment by Flauipaui** [comment]
Indeed, i had a merge conflict. 

Errors fixed after cloning again the library again from github. 

Thanks for the support
