### ISSUE TITLE
Typos within documentation

### ISSUE THREAD

**Issue by Flauipaui** [DLR-SR/ThermofluidStream#35]
Hello, 

while studying your library i have found the following typos:

1. Processes/FlowResistance.mo line 80 "turbulent" <p><span style=\"font-size: 12pt;\">Implementation of a flow resistance pipe with different selectable flow resistance functions (laminar, laminar-turb**o**lent, linear-quadratic).</span></p>
2. https://github.com/DLR-SR/ThermofluidStream/blob/c8ceaecfe4e3b7732eb7219b7548dd99bc3d303e/ThermofluidStream/Processes/Internal/FlowResistance/linearQuadraticPressureLoss.mo#L6 - resistance
3. https://github.com/DLR-SR/ThermofluidStream/blob/c8ceaecfe4e3b7732eb7219b7548dd99bc3d303e/ThermofluidStream/Processes/Internal/FlowResistance/partialPressureLoss.mo#L14 - information
4. https://github.com/DLR-SR/ThermofluidStream/blob/c8ceaecfe4e3b7732eb7219b7548dd99bc3d303e/ThermofluidStream/Processes/Internal/FlowResistance/pleaseSelectPressureLoss.mo#L11 - always
5. https://github.com/DLR-SR/ThermofluidStream/blob/c8ceaecfe4e3b7732eb7219b7548dd99bc3d303e/ThermofluidStream/Processes/Internal/PartialTurboComponent.mo#L92 - characteristics
6. https://github.com/DLR-SR/ThermofluidStream/blob/c8ceaecfe4e3b7732eb7219b7548dd99bc3d303e/ThermofluidStream/Interfaces/Inlet.mo#L41 - supposed

Please check and correct.

Bests,

**Comment by mimeissner** [comment]
Thanks for your work. I fixed the typos in 3e2fc7841fa8118c80016419cbb2e9bc79927420. 

If you want you could also create a fork, fix the typos and then make a pull request.

**Comment by Flauipaui** [comment]
yeah. i forgot about that possibility. I'll do it the next time. 

Bests,
