### ISSUE TITLE
Incorrect sum call in Boundaries.Internal.PartialVolumeN

### ISSUE THREAD

**Issue by perost** [DLR-SR/ThermofluidStream#41]
`outlet.m_flow` is not an array in `PartialVolumeN`, so `sum(outlet.m_flow)` is incorrect on this line and should just be `outlet.m_flow`:
https://github.com/DLR-SR/ThermofluidStream/blob/4c7a642e49602af76d683a1d20405fdb63fb6537/ThermofluidStream/Boundaries/Internal/PartialVolumeN.mo#L117
This used to be allowed by OpenModelica by mistake, which caused some issues since it wasn't supposed to be allowed (the Modelica specification only define `sum` for array expression).

**Comment by mimeissner** [comment]
fixed in ef31d9a470c4115b708e3a4b9904b399a68e6d3f
