### ISSUE TITLE
Invalid function input argument default binding

### ISSUE THREAD

**Issue by maltelenz** [DLR-SR/ThermofluidStream#56]
When validating `ThermofluidStream.Examples.SimpleCoolingCycle` in System Modeler:

```
Error: ThermofluidStream.Processes.Internal.TurboComponent.dp_tau_centrifugal [18:3-18:3] Invalid function input argument default binding. Input argument default binding cannot depend on non-input variables. v_s_input is an input but v_s_ref is not.
```

**Comment by maltelenz** [comment]
Do you agree this is a violation of the Modelica specification?

**Comment by tobolar** [comment]
Well, I'm not an expert to Modelica Spec. ;-)

But looking deeper in the Modelica Specification 3.5, I found in "12.4.1 Positional or Named Input Arguments of Functions"
> The default values may depend on other inputs (these dependencies must be acyclical in the function) { the values for those other inputs will then be substituted into the default values (this process may be repeated if the default value for that input depend on another input). The default values for inputs **shall not depend on non-input variables** in the
function. 

How is *shall not* interpreted then?

**Comment by maltelenz** [comment]
The Modelica specification largely aims to follow https://www.rfc-editor.org/rfc/rfc2119 , so:

> MUST NOT   This phrase, or the phrase "SHALL NOT", mean that the
>   definition is an absolute prohibition of the specification.

To be clear, System Modeler does consider this an absolute error, and will not allow building models breaking the rule you quoted.

**Comment by tobolar** [comment]
Ok, then we will implement another concept.
