### ISSUE TITLE
CoolProp compatibility

### ISSUE THREAD

**Issue by filipdvorak7** [DLR-SR/ThermofluidStream#91]
Is there any plan to make a compatibility with CoolProp (https://github.com/CoolProp/CoolProp) through the ExternalMedia? (https://github.com/modelica-3rdparty/ExternalMedia)

**Comment by dzimmer** [comment]
We have considered adding compatibility to External Media. I think it only needs a small modification to the ExternalMedia interface to make it work. (basically add the functions that we had to add to Mdoelica.Media as well). We expect the performance of these models to not be the best but is certainly better than nothing.
We may eventually do it but priority is not the highest. If someone wants to take charge of the topic, we gladly support and also accept a merge request.

**Comment by dzimmer** [comment]
In the original Modelica.Media library, the massFraction Function was missing from the interface. We simply had to add this function to our interface.

**Comment by rfranke** [comment]
OK, this should be doable :) Might be uncritical for the current version 4.0.0 of ExternalMedia not yet supporting mixtures.
Btw. I like the approach of ThermofluidStream of using specific state records with generic access functions a lot more than the generic `BaseProperties` model of `Modelica.Media`!

**Comment by dzimmer** [comment]
We will focus our effort on an interface to TIL Media and hence close this issue. If someone wants to create a CoolProp interface, a pull request is highly welcome. Meanwhile, we close this issue

**Comment by rfranke** [comment]
As said above, all you need to do is to change one line in `ExternalMedia/Media/BaseClasses/ExternalTwoPhaseMedium.mo`. Better if the missing function was added to `Modelica.Media` so that ThermofluidStream could use it instead of its own copy in `ThermofluidStream.Media.myMedia`.

**Comment by bilderbuchi** [comment]
IIUC, this would need a change in ExternalMedia or MSL Media interfaces? Maybe @casella  can weigh in on what is the best path to follow, here?

**Comment by Afsaneh6868** [comment]
Hello everyone,

I have a question regarding my simulation. I'm using the ThermofluidStream library and need to use the refrigerant R1234ze in my model. Is it possible to use the CoolProp library for this purpose?
I'm new to Modelica, so any help would be greatly appreciated.

Thank you!

**Comment by dzimmer** [comment]
You could use the CoolProp model via the External Media library (which at the moment would need a slight modification as mentioned above, links at the top). 
The alternative is the commercial (but inexpensive) TIL Media library in Dymola. 
The latter solution will have a much better simulation performance.

**Comment by tobolar** [comment]
> Hello everyone,
> 
> I have a question regarding my simulation. I'm using the ThermofluidStream library and need to use the refrigerant R1234ze in my model. Is it possible to use the CoolProp library for this purpose? I'm new to Modelica, so any help would be greatly appreciated.
> 
> Thank you!

@Afsaneh6868 If you have questions like this, please open a new issue or [discussion](https://github.com/DLR-SR/ThermofluidStream/discussions). 
This issue is yet another topic, even if about CoolProp.

**Comment by matthew-kapp** [comment]
Will the computational scheme still work with CoolProp? In other words, is it still expected to mostly end up with a BLT matrix?
